name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asttokens
  - blas
  - bottleneck=1.4.2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - importlib-metadata
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - nest-asyncio
  - numexpr
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pygments
  - python=3.10
  - python-dateutil
  - python-tzdata
  - pytz
  - pyzmq
  - setuptools
  - six
  - sqlite
  - stack_data
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - wcwidth
  - wheel
  - zipp
  - pip:
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cosinorpy==3.1
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.58.5
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mne==1.9.0
      - numpy==2.2.6
      - openpyxl==3.1.5
      - pandas==2.3.1
      - patsy==1.0.1
      - pillow==11.3.0
      - pooch==1.8.2
      - pyaml==25.7.0
      - pyparsing==3.2.3
      - pyyaml==6.0.2
      - requests==2.32.4
      - scikit-learn==1.4.2
      - scikit-optimize==0.10.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - statsmodels==0.14.5
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tqdm-joblib==0.0.4
      - urllib3==2.5.0
      - xlrd==2.0.2
